language: go
go:
  - 1.9.x
  - 1.10.x

services:
  - docker

env:
 - GOCD_VERSION=v17.10.0 CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage GOCD_PLUGIN_INSTALL_github_pr=https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/download/v1.3.5/github-pr-poller-1.3.5.jar
 - GOCD_VERSION=v18.7.0 CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage GOCD_PLUGIN_INSTALL_github_pr=https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/download/v1.3.5/github-pr-poller-1.3.5.jar

addons:
  apt:
    packages:
    - rpm

matrix:
  fast_finish: true
  allow_failures:
     - env: GOCD_VERSION=v17.10.0 CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage

before_install:
  - make before_install

script:
  - go generate -x $(glide novendor) && git diff --exit-code; code=$?; git checkout -- .; (exit	$code)
  - make testacc

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - go get github.com/goreleaser/goreleaser
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage.out

after_failure:
  docker logs gocd-server-test --tail all

deploy:
  - provider: script
    skip_cleanup: true
    script: make deploy_on_tag
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.10\.([0-9]+|x)?$ && $GOCD_VERSION =~ ^v18\.[0-9]+\.[0-9]+$
  - provider: script
    skip_cleanup: true
    script: make deploy_on_develop
    on:
      branch: develop
      condition: $TRAVIS_GO_VERSION =~ ^1\.10\.([0-9]+|x)?$ && $GOCD_VERSION =~ ^v18\.[0-9]+\.[0-9]+$
